version: '3.7'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: API
        #restart: unless-stopped
        #env_file: .env
        links:
            - nats
        depends_on:
            - nats
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
            - node_modules:/usr/app/node_modules
        command: node --experimental-modules app.js
        environment:
            NODE_ENV: development

    #PHP Service
    app:
        build:
            dockerfile: php.Dockerfile
            context: .
        restart: always
        container_name: frontend
        volumes:
            - "./frontend/:/var/www/html"
        ports:
            - "8082:80"
    nats:
        image: 'nats:2.1.9'
        container_name: nats
        #    entrypoint: "/gnatsd -DV"
        #    entrypoint: "/nats-server -p 4222 -m 8888 "
        expose:
            - '4222'
        ports:
            - '8222:8222'
        hostname: nats-server
networks:
        app-network:
            driver: bridge
volumes:
    node_modules: